# 필요 패키지 로드

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# Import text clearning libraries
import re
from bs4 import BeautifulSoup
import nltk

In [ ]:
import nltk
nltk.download("all")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 셋팅(컬럼 너비 넓게)
pd.set_option('display.max_colwidth', 200)

# 처리함수 정의
여기서 자를 단어 갯수를 변경할 수 있음.
함수 정의는 한번만 하면 됨.

In [ ]:
# Stopwords to remove from text will have little effect on the context of the text
# Stopwords in list already in lower case
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
# Custom_stopwords_for_WordCloud = ['enquire', 'developer sale', 'call enquire', 'call now', 'to enquire', 'for sale', 'new listing', 'unit sale', 'serious seller', 'exclusive listing', 'floor unit', 'new list', 'new exclusive', 'direct developer','don’t miss','call','now','to','for','new','listing','unit','serious','seller','exclusive','floor','list','direct','developer','sale','call', 'now', 'enquire', 'unit', 'floor', 'serious', 'seller', 'listing', '3','2','1', '4', '5', 'blk', 'facing','ang','mo','kio']
# Custom_stopwords_for_one_word =['enquire', 'now', 'call', 'unit', 'floor', 'serious', 'seller', 'listing', '3', '2', '1', '4', '5', 'blk', 'facing', 'ang','mo','kio']
# Custom_stopwords_for_bigrams =['call enquire', 'call now','to enquire', 'for sale', 'new listing', 'unit sale', 'serious seller', 'exclusive listing', 'floor unit', 'new list', 'new exclusive', 'direct developer', 'developer sale']
# Custom_stopwords_for_trigrams = ['new exclusive listing', 'new listing sale', 'sale new listing', 'ang mo kio', 'direct developer sales','developer sales team', 'exclusive new listing', 'call enquire new', 'brand new listing']
stop_words = stop_words #+ Custom_stopwords
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [ ]:
# Use this to deal with apostophes and abbreviation

def remove_apostrophe_abbrev(text):
    return re.sub('[^\w\s]','', text)

# Function to remove stopwords
def remove_stop_words(text):
    clean_text = []
    for word in text.split():
        if word.strip().lower() not in stop_words:
            clean_text.append(word)
            
    return " ".join(clean_text)

In [ ]:
from nltk.stem import WordNetLemmatizer 
# Init the Wordnet Lemmatizer
def lemma(text):
    lemmatizer = WordNetLemmatizer()
    word_list = nltk.word_tokenize(text)
    # print(word_list)
    # print(type)


    # Lemmatize list of words and join
    lemmatized_output = ' '.join([lemmatizer.lemmatize(w,'v') for w in word_list])
    return lemmatized_output

In [ ]:
# Use this to deal with apostophes and abbreviation

def remove_apostrophe_abbrev(text):
    return re.sub('[^\w\s]','', text)

# Function to remove stopwords
def remove_stop_words2(text):
    clean_text = []
    stop_word  = []
    for word in text.split():

        # if word.strip().lower() not in stop_words:
        #     clean_text.append(word)
        if word.strip().lower()== stop_words:  
           stop_word.append(word) 
          #  print(stop_words) 
    return print(stop_word)

In [ ]:
# Functions for cleaning text

# Remove html tags, using regex is bad idea
def remove_html_tags(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

# Remove links in text, http and https
# s? in regex means or s (case sensitive)
def remove_links(text):
    return re.sub('https?:\/\/\S+', '', text)

# Remove 's (possessive pronouns) from text
# Two kinds of apostophes found
def remove_possessive_pronoun(text):
    return re.sub("’s|'s", '', text)

# Remove between brackets and their contents
def remove_between_brackets(text):
    return re.sub('\([^]]*\)', '', text)

# Remove square brackets and their contents
def remove_between_square_brackets(text):
    return re.sub('\[[^]]*\]', '', text)

# Remove curly brackets and their contents
# Useful to remove any JavaScript scripts, though removed
# through html as above
def remove_between_curly_brackets(text):
    return re.sub('\{[^]]*\}', '', text)

def remove_n_space(text):
    return re.sub('\n', '', text)
    
def abc(text):
  word_list = nltk.word_tokenize(text)
  # print(word_list)
  # print(type(word_list))
  return word_list
def text1(text):
  text = remove_html_tags(text)
  list1 = []
  text = abc(text)
  list1.append(text[:10]) # 자를단어 갯수 변경 여기서
  flat_list = [item for sublist in list1 for item in sublist]
  # print(flat_list)
  output = ' '.join(w for w in flat_list)
  return output


def text_cleaner(text):
    text = remove_html_tags(text)
    text = remove_links(text)
    text = remove_possessive_pronoun(text)
    text = remove_apostrophe_abbrev(text)
    text = remove_between_brackets(text)
    text = remove_between_square_brackets(text)
    text = remove_between_curly_brackets(text)
    text = remove_n_space(text)
    text = text.lower()
    text = remove_stop_words(text)
    text = lemma(text)
    text = text1(text)
    # print(text)
    
    return text

# 데이터 로드

## all housetype

In [ ]:
# 15개로 잘랐던거 가져와서 10개 단어 단위로도 자른 컬럼도 하나 더 만들려고 함.
real = pd.read_csv("/content/drive/MyDrive/PropertyGuru/PreparedCSV/All_until_15words_220120.csv", index_col = 0)
real.head()

                                                                                                                                                     URL  ...       region
0       http://api.scraperapi.com/?api_key=b0560c3ca5b0704c0184a820d4e42d70&url=https://propertyguru.com.sg/listing/22010108/for-sale-the-clement-canopy  ...  Non-central
1  http://api.scraperapi.com/?api_key=b0560c3ca5b0704c0184a820d4e42d70&url=https://propertyguru.com.sg/listing/hdb-for-sale-665-yishun-avenue-4-21894619  ...          NaN
2            http://api.scraperapi.com/?api_key=b0560c3ca5b0704c0184a820d4e42d70&url=https://propertyguru.com.sg/listing/21817402/for-sale-costa-del-sol  ...  Non-central
3        http://api.scraperapi.com/?api_key=b0560c3ca5b0704c0184a820d4e42d70&url=https://propertyguru.com.sg/listing/22031191/for-sale-sennett-residence  ...      Central
4      http://api.scraperapi.com/?api_key=b0560c3ca5b0704c0184a820d4e42d70&url=https://propertyguru.com.sg/listing/21919425/for-sale-the-sail-marina-bay  ...      Central

[5 rows x 34 columns]

In [ ]:
# 바꾸고 싶은 순서대로 순서 변경
real = real[['ListingID', 'created_at','listed_date','description','Floorsize', 'Floor',
         'House_type','Lease_type', 'region','years_from_TOP','PSF_float','Tenanted','Total Unit(s)', 'Furnishing',
         'listed_year', 'pandemic',
         'address.locality', 'latitude', 'longitude', 'rooms', 'bathrooms', 'floor_size', 'price',
         'days_past', 'Condo', 'HDB', 'TOP', 'Lease', 'Free', 'Developer', 
         'image_urls','URL', 'development_properties.Completion Year','properties.url']]

In [ ]:
real.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 258702 entries, 0 to 258702
Data columns (total 34 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ListingID                               258702 non-null  float64
 1   created_at                              258701 non-null  object
 2   listed_date                             258701 non-null  object
 3   description                             258702 non-null  object
 4   Floorsize                               258702 non-null  float64
 5   Floor                                   211998 non-null  object
 6   House_type                              258702 non-null  object
 7   Lease_type                              258702 non-null  object
 8   region                                  179479 non-null  object
 9   years_from_TOP                          258701 non-null  float64
 10  PSF_float                               258702 non-null  float64
 11  Tenanted                                258682 non-null  object
 12  Total Unit(s)                           179867 non-null  float64
 13  Furnishing                              197295 non-null  object
 14  listed_year                             258701 non-null  float64
 15  pandemic                                258701 non-null  float64
 16  address.locality                        179479 non-null  object
 17  latitude                                258702 non-null  float64
 18  longitude                               258702 non-null  float64
 19  rooms                                   258691 non-null  object
 20  bathrooms                               258691 non-null  object
 21  floor_size                              258702 non-null  float64
 22  price                                   258702 non-null  float64
 23  days_past                               258702 non-null  int64
 24  Condo                                   258702 non-null  int64
 25  HDB                                     258702 non-null  int64
 26  TOP                                     258702 non-null  float64
 27  Lease                                   258702 non-null  int64
 28  Free                                    258702 non-null  int64
 29  Developer                               253618 non-null  object
 30  image_urls                              258702 non-null  object
 31  URL                                     258702 non-null  object
 32  development_properties.Completion Year  188906 non-null  float64
 33  properties.url                          258702 non-null  object
dtypes: float64(13), int64(5), object(16)
memory usage: 69.1+ MB

In [ ]:
# description에 결측치 존재하는 것 제거하고 단어자르고 저장 for 전체 데이터타입

#1) description이 없는 결측치행 제거
real.dropna(subset = ['description'], axis = 0, inplace = True)

#2) 처리 진행
real["descrip10"] = real["description"].apply(text_cleaner)

#3) 단어잘림처리 잘 됐는지 확인
real["descrip10"].head()

0              lovely 4br unit seaview high floor sale lovely 4 bedroom
1        corner renovate jumbo nice blk 665 jumbo multi generation unit
2    call enquire well maintain renovate unit currently tenant end soon
3           call enquire nice house well maintain face south windy pool
4            call enquire 3study unit serious seller full bay view unit
Name: descrip10, dtype: object

In [ ]:
# 4) exporting
real.to_csv("/content/drive/MyDrive/PropertyGuru/PreparedCSV/All_until_10words_220120.csv")

In [ ]:
real[['description', 'descrip10']].head()

                                                                                               description                                                           descrip10
0                 lovely 4br unit seaview high floor sale lovely 4 bedroom clement canopy sale attention 4            lovely 4br unit seaview high floor sale lovely 4 bedroom
1               corner renovate jumbo nice blk 665 jumbo multi generation unit corner rare 4 full bedrooms      corner renovate jumbo nice blk 665 jumbo multi generation unit
2  call enquire well maintain renovate unit currently tenant end soon suitable stay next upcoming bayshore  call enquire well maintain renovate unit currently tenant end soon
3                   call enquire nice house well maintain face south windy pool view good size bedroom mrt         call enquire nice house well maintain face south windy pool
4                  call enquire 3study unit serious seller full bay view unit high floor 20 part singapore          call enquire 3study unit serious seller full bay view unit

## Condo

In [ ]:
# 샘플나누기
real_Condo = real[real.Condo == 1]

# 처리 진행
real_Condo["descrip10"] = real_Condo["description"].apply(text_cleaner)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
# 확인
real_Condo[['description', 'descrip10']].head()

                                                                                               description                                                           descrip10
0                 lovely 4br unit seaview high floor sale lovely 4 bedroom clement canopy sale attention 4            lovely 4br unit seaview high floor sale lovely 4 bedroom
2  call enquire well maintain renovate unit currently tenant end soon suitable stay next upcoming bayshore  call enquire well maintain renovate unit currently tenant end soon
3                   call enquire nice house well maintain face south windy pool view good size bedroom mrt         call enquire nice house well maintain face south windy pool
5                               boon keng mrt mins 8 riversuites high floor 3br 980ft2 sale call cy 968 18              boon keng mrt mins 8 riversuites high floor 3br 980ft2
6                  tenant high floor 2 plus study qbay sale sell almost launch price development much seek                tenant high floor 2 plus study qbay sale sell almost

In [ ]:
# exporting
real_Condo.to_csv("/content/drive/MyDrive/PropertyGuru/PreparedCSV/Condo_description_until_10words_220120.csv")

## HDB

In [ ]:
# 샘플나누기
real_HDB = real[real.HDB ==1]

# 처리 진행
real_HDB["descrip10"] = real_HDB["description"].apply(text_cleaner)

# 확인
real_HDB[['description', 'descrip10']].head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

                                                                                             description                                                        descrip10
1             corner renovate jumbo nice blk 665 jumbo multi generation unit corner rare 4 full bedrooms   corner renovate jumbo nice blk 665 jumbo multi generation unit
11       mature township amenities door step sale 4a blk 267 bishan street 24 property information lease       mature township amenities door step sale 4a blk 267 bishan
15                    high floor door door unit rare gem flat upgrade toilet master room high floor well           high floor door door unit rare gem flat upgrade toilet
16  scholar block scholar block point block low floor lovers corner renovate chinese eligible cool windy  scholar block scholar block point block low floor lovers corner
19                spacious 5i point block sale list spacious 5 room flat high floor lot privacy greenery           spacious 5i point block sale list spacious 5 room flat

In [ ]:
# exporting
real_HDB.to_csv("/content/drive/MyDrive/PropertyGuru/PreparedCSV/HDB_description_until_10words_220120.csv")

## other

In [ ]:
# 샘플나누기
real_other = real[real.House_type == 'other']

In [ ]:
real_other.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35707 entries, 4 to 258702
Data columns (total 35 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   ListingID                               35707 non-null  float64
 1   created_at                              35707 non-null  object
 2   listed_date                             35707 non-null  object
 3   description                             35707 non-null  object
 4   Floorsize                               35707 non-null  float64
 5   Floor                                   26568 non-null  object
 6   House_type                              35707 non-null  object
 7   Lease_type                              35707 non-null  object
 8   region                                  35707 non-null  object
 9   years_from_TOP                          35707 non-null  float64
 10  PSF_float                               35707 non-null  float64
 11  Tenanted                                35704 non-null  object
 12  Total Unit(s)                           33893 non-null  float64
 13  Furnishing                              28226 non-null  object
 14  listed_year                             35707 non-null  float64
 15  pandemic                                35707 non-null  float64
 16  address.locality                        35707 non-null  object
 17  latitude                                35707 non-null  float64
 18  longitude                               35707 non-null  float64
 19  rooms                                   35707 non-null  object
 20  bathrooms                               35707 non-null  object
 21  floor_size                              35707 non-null  float64
 22  price                                   35707 non-null  float64
 23  days_past                               35707 non-null  int64
 24  Condo                                   35707 non-null  int64
 25  HDB                                     35707 non-null  int64
 26  TOP                                     35707 non-null  float64
 27  Lease                                   35707 non-null  int64
 28  Free                                    35707 non-null  int64
 29  Developer                               34255 non-null  object
 30  image_urls                              35707 non-null  object
 31  URL                                     35707 non-null  object
 32  development_properties.Completion Year  28245 non-null  float64
 33  properties.url                          35707 non-null  object
 34  descrip10                               35707 non-null  object
dtypes: float64(13), int64(5), object(17)
memory usage: 9.8+ MB

In [ ]:
# description이 없는 결측치행 제거
real_other.dropna(subset = ['description'], axis = 0, inplace = True)
len(real_other)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

35707

In [ ]:
# 처리 진행
real_other["descrip10"] = real_other["description"].apply(text_cleaner)

# 단어잘림처리 잘 됐는지 확인
real_other[['description', 'descrip10']].head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                                                                                           description                                                                 descrip10
4              call enquire 3study unit serious seller full bay view unit high floor 20 part singapore                call enquire 3study unit serious seller full bay view unit
13  s17psf freehold condo prime d9 location unbelievable price rare renovate unit sale 3 large ensuite  s17psf freehold condo prime d9 location unbelievable price rare renovate
32                   call enquire high floor unit 2 bed 2 bath tenant till may 2020 fantastic location                          call enquire high floor unit 2 bed 2 bath tenant
52    everything door step awesome lifestyle live pool face unit sell vacant price unit currently look           everything door step awesome lifestyle live pool face unit sell
53        whimsical bungalow sky brand new ready stay unit oliv whimsical bungalows sky boast open yet           whimsical bungalow sky brand new ready stay unit oliv whimsical

In [ ]:
# exporting
real_other.to_csv("/content/drive/MyDrive/PropertyGuru/PreparedCSV/othertype_description_until_10words_220120.csv")

# 끝

In [ ]:
#@title 중복문장 제거 원한다면 다음 활용 

# Input full file path 
# real = pd.read_csv("/content/drive/MyDrive/PropertyGuru/PreparedCSV/preprocessed_data_2.csv", index_col = 0) #최초코드
# description 문장 중복 제거
# real.drop_duplicates(['description'], keep='first', inplace=True, ignore_index=False)